// Danh sách ngân hàng Việt Nam phổ biến. `code` khớp với tên viết tắt dùng bởi
// các dịch vụ tạo mã QR VietQR (dùng lại được khi làm tính năng QR nhận thanh toán).
export type Bank = { code: string; name: string };

export const VIETNAM_BANKS: Bank[] = [
  { code: "vietcombank", name: "Vietcombank" },
  { code: "vietinbank", name: "VietinBank" },
  { code: "bidv", name: "BIDV" },
  { code: "agribank", name: "Agribank" },
  { code: "techcombank", name: "Techcombank" },
  { code: "mbbank", name: "MB Bank" },
  { code: "acb", name: "ACB" },
  { code: "vpbank", name: "VPBank" },
  { code: "sacombank", name: "Sacombank" },
  { code: "tpbank", name: "TPBank" },
  { code: "hdbank", name: "HDBank" },
  { code: "shb", name: "SHB" },
  { code: "vib", name: "VIB" },
  { code: "eximbank", name: "Eximbank" },
  { code: "seabank", name: "SeABank" },
  { code: "msb", name: "MSB" },
  { code: "ocb", name: "OCB" },
  { code: "abbank", name: "ABBANK" },
  { code: "bacabank", name: "Bac A Bank" },
  { code: "pvcombank", name: "PVcomBank" },
  { code: "namabank", name: "Nam A Bank" },
  { code: "kienlongbank", name: "KienlongBank" },
  { code: "pgbank", name: "PGBank" },
  { code: "saigonbank", name: "SaigonBank" },
  { code: "baovietbank", name: "BaoViet Bank" },
  { code: "lienvietpostbank", name: "LienVietPostBank" },
  { code: "vietbank", name: "VietBank" },
  { code: "scb", name: "SCB" },
  { code: "gpbank", name: "GPBank" },
  { code: "coopbank", name: "Ngân hàng Hợp tác xã (Co-opBank)" },
  { code: "cake", name: "CAKE by VPBank" },
  { code: "ubank", name: "Ubank by VPBank" },
  { code: "timo", name: "Timo" },
  { code: "shinhan", name: "Shinhan Bank" },
  { code: "woori", name: "Woori Bank" },
  { code: "cimb", name: "CIMB Bank" },
  { code: "uob", name: "UOB Việt Nam" },
];
