-- Chạy trong Supabase SQL Editor

alter table public.portfolio_posts add column topic text;
alter table public.tags add column is_category boolean not null default false;

update public.tags set is_category = true where name in (
  'banner mạng xã hội',
  'banner quảng cáo kỹ thuật số',
  'trang trí gian hàng sàn tmđt',
  'poster',
  'standee',
  'băng rôn',
  'phướn',
  'infographic',
  'bảng hiệu',
  'biển quảng cáo ngoài trời',
  'billboard',
  'signage',
  'thiết kế logo',
  'bộ văn phòng cơ bản',
  'stationery kit',
  'cẩm nang thương hiệu',
  'brand guidelines',
  'hồ sơ năng lực',
  'profile công ty',
  'catalogue sản phẩm',
  'thiết kế slide',
  'pitch deck',
  'nhãn mác sản phẩm',
  'hộp giấy',
  'hộp quà tặng',
  'box design',
  'túi giấy',
  'túi vải',
  'túi nilon',
  'shopping bag',
  'bao bì màng mềm',
  'pouch',
  'sachet',
  'thẻ bài',
  'tag treo',
  'tờ rơi',
  'tờ gấp',
  'flyer',
  'brochure',
  'leaflet',
  'bìa sách',
  'bìa truyện',
  'bìa tạp chí',
  'dàn trang nội dung',
  'thiệp mời',
  'thiệp cưới',
  'invitation card',
  'thực đơn',
  'menu',
  'lịch',
  'voucher',
  'thẻ giảm giá',
  'landing page',
  'giao diện website toàn diện',
  'multi-page web',
  'giao diện ứng dụng di động',
  'mobile app ui',
  'giao diện hệ thống quản trị',
  'admin dashboard',
  'giao diện trò chơi',
  'game ui',
  'hud',
  'bộ biểu tượng',
  'icon pack',
  'chỉnh ảnh sản phẩm tmđt',
  'e-commerce retouching',
  'retouch ảnh chân dung',
  'lookbook',
  'ảnh cưới',
  'cắt ghép ảnh nghệ thuật',
  'photo manipulation',
  'xóa nền',
  'tách nền',
  'background removal',
  'phục chế ảnh cũ',
  'photo restoration',
  'edit video ngắn',
  'tiktok',
  'reels',
  'shorts',
  'video quảng cáo',
  'video doanh nghiệp',
  'promo video',
  'corporate video',
  'đồ họa chuyển động',
  'motion graphics',
  'explainer video',
  'hiệu ứng chữ',
  'kinetic typography',
  'intro',
  'outro',
  'logo animation',
  'tranh minh họa',
  'illustration',
  'họa tiết thời trang',
  'pattern design',
  'thiết kế áo thun',
  't-shirt design',
  'concept art',
  'sticker',
  'emoji độc quyền'
);
